from enum import StrEnum


class ErrorCode(StrEnum):
    # Device
    DEVICE_NOT_FOUND = "device_not_found"
    DEVICE_INVALID_REQUEST = "device_invalid_request"
    DEVICE_NAME_TAKEN = "device_name_taken"
    DEVICE_CONFIG_CONFLICT = "device_config_conflict"
    DEVICE_OFFLINE = "device_offline"
    # Workspace
    WORKSPACE_NOT_FOUND = "workspace_not_found"
    WORKSPACE_PERMISSION_DENIED = "workspace_permission_denied"
    WORKSPACE_SYMLINK_ESCAPE = "workspace_symlink_escape"
    WORKSPACE_SOFT_LOCKED = "workspace_soft_locked"
    WORKSPACE_UPLOAD_TOO_LARGE = "workspace_upload_too_large"
    WORKSPACE_QUOTA_EXCEEDED = "workspace_quota_exceeded"
    WORKSPACE_INVALID_SKILL_FORMAT = "workspace_invalid_skill_format"
    WORKSPACE_BLOCKED_PATH = "workspace_blocked_path"
    WORKSPACE_FILE_TOO_LARGE_TO_EDIT = "workspace_file_too_large_to_edit"
    WORKSPACE_DIRECTORY_TOO_LARGE = "workspace_directory_too_large"
    WORKSPACE_FILE_CHANGED = "workspace_file_changed"
    WORKSPACE_STORAGE_UNAVAILABLE = "workspace_storage_unavailable"
    WORKSPACE_STORAGE_ERROR = "workspace_storage_error"
    WORKSPACE_TRANSFER_BUSY = "workspace_transfer_busy"
    WORKSPACE_TRANSFER_TIMEOUT = "workspace_transfer_timeout"
    WORKSPACE_TRANSFER_INTEGRITY_FAILED = "workspace_transfer_integrity_failed"
    WORKSPACE_INVALID_REQUEST = "workspace_invalid_request"
    WORKSPACE_REF_CONFLICT = "workspace_ref_conflict"
    # Tool
    TOOL_AMBIGUOUS_EDIT = "tool_ambiguous_edit"
    TOOL_NO_MATCH = "tool_no_match"
    TOOL_IS_DIRECTORY = "tool_is_directory"
    TOOL_IS_FILE = "tool_is_file"
    TOOL_NOT_A_DIRECTORY = "tool_not_a_directory"
    TOOL_INVALID_NOTEBOOK = "tool_invalid_notebook"
    TOOL_CELL_INDEX_OUT_OF_RANGE = "tool_cell_index_out_of_range"
    TOOL_INVALID_ARGS = "tool_invalid_args"
    TOOL_INVALID_REGEX = "tool_invalid_regex"
    TOOL_INVALID_GLOB = "tool_invalid_glob"
    TOOL_EXEC_TIMEOUT = "tool_exec_timeout"
    TOOL_EXEC_FAILED = "tool_exec_failed"
    TOOL_EXEC_SESSION_NOT_FOUND = "tool_exec_session_not_found"
    TOOL_EXEC_STDIN_CLOSED = "tool_exec_stdin_closed"
    TOOL_EXEC_INTERRUPT_FAILED = "tool_exec_interrupt_failed"
    TOOL_SHELL_UNAVAILABLE = "tool_shell_unavailable"
    TOOL_PTY_UNAVAILABLE = "tool_pty_unavailable"
    TOOL_SHELL_LOGIN_UNSUPPORTED = "tool_shell_login_unsupported"
    TOOL_CLIENT_SHUTTING_DOWN = "tool_client_shutting_down"
    TOOL_CONTENT_CONVERSION_BUSY = "tool_content_conversion_busy"
    TOOL_CONTENT_CONVERSION_RESOURCE_EXCEEDED = "tool_content_conversion_resource_exceeded"
    TOOL_CONTENT_CONVERSION_FAILED = "tool_content_conversion_failed"
    TOOL_COMMAND_DENIED = "tool_command_denied"
    TOOL_ENV_NOT_ALLOWED = "tool_env_not_allowed"
    TOOL_CWD_OUTSIDE_WORKSPACE = "tool_cwd_outside_workspace"
    TOOL_PATH_OUTSIDE_WORKSPACE = "tool_path_outside_workspace"
    TOOL_DEVICE_UNREACHABLE = "tool_device_unreachable"
    TOOL_DEVICE_BUSY = "tool_device_busy"
    TOOL_EXECUTION_OUTCOME_UNKNOWN = "tool_execution_outcome_unknown"
    TOOL_CHANNEL_NOT_CONFIGURED = "tool_channel_not_configured"
    TOOL_UNSUPPORTED_MEDIA = "tool_unsupported_media"
    TOOL_DELIVERY_FAILED = "tool_delivery_failed"
    TOOL_INVALID_SCHEDULE = "tool_invalid_schedule"
    TOOL_MISSING_REQUIRED_FIELD = "tool_missing_required_field"
    TOOL_DB_ERROR = "tool_db_error"
    TOOL_CRON_JOB_NOT_FOUND = "tool_cron_job_not_found"
    TOOL_MCP_UNAVAILABLE = "tool_mcp_unavailable"
    TOOL_MCP_ERROR = "tool_mcp_error"
    TOOL_MCP_MESSAGE_TOO_LARGE = "tool_mcp_message_too_large"
    TOOL_MCP_INVALID_RESULT = "tool_mcp_invalid_result"
    TOOL_RESULT_TOO_LARGE = "tool_result_too_large"
    # Network
    NETWORK_SSRF_BLOCKED = "network_ssrf_blocked"
    NETWORK_DNS_FAILED = "network_dns_failed"
    NETWORK_TIMEOUT = "network_timeout"
    NETWORK_HTTP_ERROR = "network_http_error"
    # Protocol
    PROTOCOL_MALFORMED_FRAME = "protocol_malformed_frame"
    PROTOCOL_UNKNOWN_TYPE = "protocol_unknown_type"
    PROTOCOL_VERSION_MISMATCH = "protocol_version_mismatch"
    PROTOCOL_TRANSFER_UNKNOWN_ID = "protocol_transfer_unknown_id"
    # MCP
    MCP_WITHIN_SERVER_COLLISION = "mcp_within_server_collision"
    MCP_SCHEMA_COLLISION = "mcp_schema_collision"
    MCP_OWNER_SCHEMA_LIMIT = "mcp_owner_schema_limit"
    MCP_SPAWN_FAILED = "mcp_spawn_failed"
    MCP_MESSAGE_TOO_LARGE = "mcp_message_too_large"
    MCP_SECRET_TRANSPORT_INSECURE = "mcp_secret_transport_insecure"
    # Auth
    AUTH_UNAUTHORIZED = "auth_unauthorized"
    AUTH_LAST_ADMIN_REQUIRED = "auth_last_admin_required"
    AUTH_EMAIL_TAKEN = "auth_email_taken"
    AUTH_INVALID_CREDENTIALS = "auth_invalid_credentials"
    AUTH_FORBIDDEN = "auth_forbidden"
    USER_NOT_FOUND = "user_not_found"
    # Config
    CONFIG_VALIDATION_FAILED = "config_validation_failed"
    # Chat/provider
    NOT_FOUND = "not_found"
    INVALID_MESSAGE_CONTENT = "invalid_message_content"
    INVALID_CURSOR = "invalid_cursor"
    PROVIDER_NOT_CONFIGURED = "provider_not_configured"
    PROVIDER_UNAVAILABLE = "provider_unavailable"
    PROVIDER_PROTOCOL_ERROR = "provider_protocol_error"
    # System
    SERVER_RESTART = "server_restart"
    USER_CANCELLED = "user_cancelled"
